setTimeout(() => console.log('hi'));
setTimeout(() => console.log('hi 5'), 5000);
console.log('hello');
console.log('hello');
console.log('hello');
console.log('hello');
console.log('hello');
console.log('hello');
console.log('hello');
console.log('hello');